spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/techchallenge
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
client:
  mercado-pago:
    user_id: 123456
    pos_id: 123456
    external_store_id: "X"
    external_pos_id: "X"
    auth_header: "Bearer TEST-X"